TCA Support: Mnemonic Interactor
zcash-hackworks/MnemonicSwift pull request #19
Opened 2022-01-29 12:20 UTC by adamstener

This PR closes issue [#9](https://github.com/zcash-hackworks/MnemonicSwift/issues/9)

We add an interactor that wraps the API usage into function properties that can easily be mocked or used inside a TCA reducer dependency.  

SwiftLint also picked up on some formatting issues that were addressed.

2022-01-31 22:54 UTC, pacu commented
Looks good to me, but it feels out of place. The pattern used by PointFree folks is to extract these wrappers to their on package. Though, it feels as an overkill.

I've quickly googled a little bit and read through the swift.org SPM section.

this forum post might be suitable for creating a package that is purely MnemonicSwift and another for people using TCA 
https://forums.swift.org/t/how-to-produce-multiple-libraries-from-one-package/18478

2022-01-31 22:56 UTC, pacu requested changes
See comment https://github.com/zcash-hackworks/MnemonicSwift/pull/19#issuecomment-1026292385

2022-01-31 23:11 UTC, adamstener commented
> Looks good to me, but it feels out of place. The pattern used by PointFree folks is to extract these wrappers to their on package. Though, it feels as an overkill.
> 
> 
> 
> I've quickly googled a little bit and read through the swift.org SPM section.
> 
> 
> 
> this forum post might be suitable for creating a package that is purely MnemonicSwift and another for people using TCA 
> 
> https://forums.swift.org/t/how-to-produce-multiple-libraries-from-one-package/18478
> 
> 
> 
> 

Wrapping a dependency in this way is not specific to TCA.  Notice that we did not need to add a dependency on that framework at all here.  This is just a different way of interacting with this dependency such that it can be easily mocked without creating an unnecessary protocol and it allows for building new test stars easily.  That being said, if you would like to see this live somewhere else I'm happy to move wherever you see fit!

2022-02-01 16:29 UTC, pacu commented
> 

adding package for a wrapper class sounds like too much. So I'd go for documenting intended uses for the Interactor and leave it here.

2022-02-02 17:55 UTC, merged